.PHONY:all

SOURCE = main.c cal.c foo.c bar.h crr.s crd.s
OBJS = /home/eden
add_SOURCE = $(addprefix $(OBJS)/, $(SOURCE))
result = $(filter %.c %r.s, $(add_SOURCE))

all:

	@echo $(result)


